### ISSUE TITLE
timeAgo cause app crash

### ISSUE THREAD

**Issue by franklingu** [MatthewYork/DateTools#81] opened 2015-06-04 09:11 UTC
for DateTools, I do think either clearly specify that even if cocoapods is used, we still need to drag the bundle over, or have this automatically solved...

**Comment by joeblau** [comment] 2015-06-06 07:03
I'm noticing the same thing.

**Comment by jacksonh** [comment] 2015-06-09 16:44
Probably a duplicate of this issue (which includes a workaround): https://github.com/MatthewYork/DateTools/issues/69

**Comment by joeblau** [comment] 2015-06-09 18:05
Yep, this can be marked as a duplicate.  I had to drag the bundle with the localized strings into my project and everything was fixed.

**Comment by franklingu** [comment] 2015-06-10 07:12
Can this be solved with shell script?

**Comment by franklingu** [comment] 2015-06-10 07:13
Yes. This is duplicated. Can be closed therefore

**Comment by MatthewYork** [comment] 2015-06-22 14:11
Closed

**Comment by MatthewYork** [comment] 2015-06-22 14:12
Fixed in #84

**Closed by MatthewYork** 2015-06-22 14:12 UTC
