### ISSUE TITLE
Swift 3 Compile Error: Value of type 'Date?' has no member 'timeAgoSinceNow'

### ISSUE THREAD

**Issue by mxie1563** [MatthewYork/DateTools#191] opened 2017-02-03 16:32 UTC
Just updated the Datetools using "pod update" few minutes ago, to version 2.0.0. After that, this error shown up in the build. Can you check to see whether the last merge has anything to do with it. Thanks!

**Comment by akaralar** [comment] 2017-02-03 17:04
I'm having the same error

**Comment by MatthewYork** [comment] 2017-02-03 17:09
Looking into this. Probably due to an access modifier. Will push a fix within the day

**Comment by MatthewYork** [comment] 2017-02-03 17:13
Please be advised that the import name may be changed. This podspec is now DateToolsSwift

**Comment by akaralar** [comment] 2017-02-03 18:06
Yeah that fixed it for me, thanks!

**Comment by MatthewYork** [comment] 2017-02-03 20:24
Good deal! Yeah, we will be catching up on documentation over the weekend.

**Comment by mxie1563** [comment] 2017-02-04 01:24
the podspec name update resolved the issue.

**Comment by finddoc** [comment] 2017-02-08 04:11
seems cannot pod 'DateToolsSwift'

**Comment by MatthewYork** [comment] 2017-03-04 04:13
DateToolsSwift is working well as of version 2.0.2. I am closing this issue. Thanks!

**Closed by MatthewYork** 2017-03-04 04:13 UTC

**Comment by SamBallantyne** [comment] 2017-04-28 18:14
I'm having this issue in 2.0.3 -- should this be re-opened?

**Comment by rostopira** [comment] 2017-05-02 13:18
Same issue on 2.0.3, regression?
